services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=pokemon
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  seed:
    container_name: seed
    build: .\database
    links:
      - mongodb

  api:
    image: fiap/quarkus-joinha:1.0.0
    container_name: api
    ports:
      - "8080:8080"
    links:
      - mongodb
    entrypoint: ./entrypoint.sh
